# Generated by Django 3.0.3 on 2020-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200220_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='selected',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
