# Generated by Django 3.0.3 on 2020-03-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_userwithtodolists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='selected',
            new_name='isdone',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
